package com.ite012.dynamicgui;

import java.util.ArrayList;

public class GUI extends javax.swing.JFrame {

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelBackground = new javax.swing.JPanel();
        panelBorder = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        addEntryButton = new javax.swing.JButton();
        removeEntryButton = new javax.swing.JButton();
        tableHeadersPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 500));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 500));

        panelBackground.setBackground(new java.awt.Color(204, 204, 204));
        panelBackground.setPreferredSize(new java.awt.Dimension(450, 2000));
        panelBackground.setLayout(new java.awt.CardLayout(10, 10));

        panelBorder.setBackground(new java.awt.Color(204, 204, 204));
        panelBorder.setPreferredSize(new java.awt.Dimension(900, 112));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10);
        flowLayout1.setAlignOnBaseline(true);
        panelBorder.setLayout(flowLayout1);

        headerPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerPanel.setPreferredSize(new java.awt.Dimension(900, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Transaction History");

        addEntryButton.setBackground(new java.awt.Color(51, 153, 255));
        addEntryButton.setForeground(new java.awt.Color(255, 255, 255));
        addEntryButton.setText("Add entry");
        addEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addEntryButtonMousePressed(evt);
            }
        });

        removeEntryButton.setBackground(new java.awt.Color(255, 0, 0));
        removeEntryButton.setForeground(new java.awt.Color(255, 255, 255));
        removeEntryButton.setText("Remove entry");
        removeEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                removeEntryButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEntryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeEntryButton)
                        .addGap(0, 522, Short.MAX_VALUE))
                    .addComponent(jSeparator10))
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addEntryButton)
                    .addComponent(removeEntryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder.add(headerPanel);

        tableHeadersPanel.setBackground(new java.awt.Color(204, 204, 204));
        tableHeadersPanel.setPreferredSize(new java.awt.Dimension(900, 30));
        tableHeadersPanel.setLayout(new java.awt.GridLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date & Time");
        tableHeadersPanel.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Amount");
        tableHeadersPanel.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Reference Number");
        tableHeadersPanel.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Status (IGNORE THIS)");
        tableHeadersPanel.add(jLabel12);

        panelBorder.add(tableHeadersPanel);

        panelBackground.add(panelBorder, "card2");

        jScrollPane1.setViewportView(panelBackground);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEntryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEntryButtonMousePressed
        panelBorder.add(new TransactionEntryPanel("MM/DD/YYYY hh:mm:ss", "9999", 
            "123456789", "OK"));
        
        revalidate();
        repaint();
        
    }//GEN-LAST:event_addEntryButtonMousePressed

    private void removeEntryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEntryButtonMousePressed
        ArrayList<java.awt.Component> transactionEntries = new ArrayList<java.awt.Component>();
        
        for (java.awt.Component c : panelBorder.getComponents()) {
            if (c instanceof TransactionEntryPanel) {
                transactionEntries.add(c);
            }
        }
        
        if (transactionEntries.size() > 0) {
            panelBorder.remove(transactionEntries.getLast());
        }
        
        revalidate();
        repaint();
    }//GEN-LAST:event_removeEntryButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntryButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBorder;
    private javax.swing.JButton removeEntryButton;
    private javax.swing.JPanel tableHeadersPanel;
    // End of variables declaration//GEN-END:variables
}
