package com.ite012.group4.lms;    

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

public class GUI extends javax.swing.JFrame {

    ArrayList<Admin> admins = new ArrayList();
    ArrayList<Client> clients = new ArrayList();
    private Admin currentAdmin;
    private Client currentClient;
    private int userMode = User.ADMIN;
    private javax.swing.JPanel activePage = new javax.swing.JPanel();
    
    
    public GUI() {
        initComponents();       

        Helpers.loadIcons();
        
        loginGraphicLabel.setIcon(Helpers.resizeIcon("loginGraphicsIcon", 330, 330));
        applicationPageToggleButton.setIcon(Helpers.resizeIcon("applicationIcon", 15, 15));
        statusPageToggleButton.setIcon(Helpers.resizeIcon("statusIcon", 15, 15));  
        paymentPageToggleButton.setIcon(Helpers.resizeIcon("paymentIcon", 15, 15));       
        repaymentPageToggleButton.setIcon(Helpers.resizeIcon("repaymentIcon", 15, 15));
        searchPageToggleButton.setIcon(Helpers.resizeIcon("searchIcon", 15, 15));
        searchSubmitButton.setIcon(Helpers.resizeIcon("searchIcon", 20, 20));
        reportPageToggleButton.setIcon(Helpers.resizeIcon("reportIcon", 15, 15));
        aboutPageToggleButton.setIcon(Helpers.resizeIcon("aboutIcon", 15, 15));

        ImageFileChooser imageChooser1 = new ImageFileChooser();
        formPanel.add(imageChooser1);

        Helpers.loadAllAdmins(admins);
        Helpers.loadAllClients(clients);
        
        backgroundPanel = new JPanelBackground(Helpers.imageDirectory + "background.jpg");
        backgroundPanel.setPreferredSize(new java.awt.Dimension(960, 490));
        backgroundPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 0));
        
        backgroundPanel.add(loginPagePanel);
        windowPanel.add(backgroundPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentPagePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        statusPagePanel = new javax.swing.JPanel();
        repaymentPagePanel = new javax.swing.JPanel();
        reportPagePanel = new javax.swing.JPanel();
        searchPagePadding1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(800, 5), new java.awt.Dimension(470, 5), new java.awt.Dimension(800, 5));
        searchField1 = new javax.swing.JTextField();
        searchSubmitButton1 = new javax.swing.JButton();
        searchResultsLabel1 = new javax.swing.JLabel();
        searchResultsScrollPane1 = new javax.swing.JScrollPane();
        reportListPanel = new javax.swing.JPanel();
        menuButtonGroup = new javax.swing.ButtonGroup();
        regUserTypeContentPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 50), new java.awt.Dimension(200, 170), new java.awt.Dimension(1, 50));
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(300, 20), new java.awt.Dimension(80, 0));
        regClientButton = new javax.swing.JButton();
        regAdminButton = new javax.swing.JButton();
        registerContentPanel = new javax.swing.JPanel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 50), new java.awt.Dimension(200, 50), new java.awt.Dimension(200, 50));
        backToLoginButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 5), new java.awt.Dimension(150, 5), new java.awt.Dimension(30, 5));
        registrationLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        regFirstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        regMiddleNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        regLastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        regEmailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        regContactNumLabel = new javax.swing.JLabel();
        contactNumField = new javax.swing.JTextField();
        regUsernameLabel = new javax.swing.JLabel();
        regUsernameField = new javax.swing.JTextField();
        regPasswordLabel = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        regConfirmPassLabel = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(100, 0));
        confirmPassFieldErrorLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(320, 0), new java.awt.Dimension(320, 0), new java.awt.Dimension(320, 0));
        registerSubmitButton = new javax.swing.JButton();
        applicationClientPagePanel = new javax.swing.JPanel();
        applicationClientPaddingPanel = new javax.swing.JPanel();
        applicationContentPanel = new javax.swing.JPanel();
        applyForALoanLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        submitApplicationButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        applicationAdminPagePanel = new javax.swing.JPanel();
        applicationAdminPaddingPanel = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        applicationListPanel = new javax.swing.JPanel();
        applicationEntryPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 5), new java.awt.Dimension(230, 5), new java.awt.Dimension(300, 5));
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        applicationApprovalPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        searchPagePanel = new javax.swing.JPanel();
        searchPagePadding = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchSubmitButton = new javax.swing.JButton();
        searchResultsLabel = new javax.swing.JLabel();
        searchResultsScrollPane = new javax.swing.JScrollPane();
        searchResultsPanel = new javax.swing.JPanel();
        aboutPagePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        menuBarPanel = new javax.swing.JPanel();
        programNameLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(350, 0), new java.awt.Dimension(50, 32767));
        applicationPageToggleButton = new javax.swing.JToggleButton();
        paymentPageToggleButton = new javax.swing.JToggleButton();
        repaymentPageToggleButton = new javax.swing.JToggleButton();
        releasePageToggleButton = new javax.swing.JToggleButton();
        reportPageToggleButton = new javax.swing.JToggleButton();
        searchPageToggleButton = new javax.swing.JToggleButton();
        logoutButton = new javax.swing.JButton();
        statusPageToggleButton = new javax.swing.JToggleButton();
        aboutPageToggleButton = new javax.swing.JToggleButton();
        loginPagePanel = new javax.swing.JPanel();
        loginPaddingPanel = new javax.swing.JSplitPane();
        loginGraphicsPanel = new javax.swing.JPanel();
        loginGraphicLabel = new javax.swing.JLabel();
        loginContentPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 50), new java.awt.Dimension(200, 50), new java.awt.Dimension(200, 50));
        companyNameLabel = new javax.swing.JLabel();
        loginUsernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(80, 0));
        usernameFieldErrorLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(80, 0));
        passwordFieldErrorLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(300, 12), new java.awt.Dimension(200, 0));
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        windowPanel = new javax.swing.JPanel();

        paymentPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        paymentPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Payment Window");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout paymentPagePanelLayout = new javax.swing.GroupLayout(paymentPagePanel);
        paymentPagePanel.setLayout(paymentPagePanelLayout);
        paymentPagePanelLayout.setHorizontalGroup(
            paymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        paymentPagePanelLayout.setVerticalGroup(
            paymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout statusPagePanelLayout = new javax.swing.GroupLayout(statusPagePanel);
        statusPagePanel.setLayout(statusPagePanelLayout);
        statusPagePanelLayout.setHorizontalGroup(
            statusPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        statusPagePanelLayout.setVerticalGroup(
            statusPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout repaymentPagePanelLayout = new javax.swing.GroupLayout(repaymentPagePanel);
        repaymentPagePanel.setLayout(repaymentPagePanelLayout);
        repaymentPagePanelLayout.setHorizontalGroup(
            repaymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        repaymentPagePanelLayout.setVerticalGroup(
            repaymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        reportPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        reportPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));
        reportPagePanel.setLayout(new java.awt.BorderLayout());

        searchPagePadding1.setBackground(new java.awt.Color(204, 204, 204));
        searchPagePadding1.setOpaque(false);

        jLabel6.setText("Enter application number");
        searchPagePadding1.add(jLabel6);
        searchPagePadding1.add(filler12);

        searchField1.setBackground(new java.awt.Color(255, 255, 255));
        searchField1.setForeground(new java.awt.Color(51, 51, 51));
        searchField1.setPreferredSize(new java.awt.Dimension(500, 50));
        searchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchField1ActionPerformed(evt);
            }
        });
        searchPagePadding1.add(searchField1);

        searchSubmitButton1.setBackground(new java.awt.Color(153, 153, 153));
        searchSubmitButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchSubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        searchSubmitButton1.setText("Search");
        searchSubmitButton1.setBorder(null);
        searchSubmitButton1.setIconTextGap(10);
        searchSubmitButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        searchSubmitButton1.setSelected(true);
        searchSubmitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchSubmitButton1MousePressed(evt);
            }
        });
        searchPagePadding1.add(searchSubmitButton1);

        searchResultsLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchResultsLabel1.setForeground(new java.awt.Color(51, 51, 51));
        searchResultsLabel1.setText("Date and Time                    Amount                       Reference ID");
        searchResultsLabel1.setPreferredSize(new java.awt.Dimension(600, 24));
        searchResultsLabel1.setRequestFocusEnabled(false);
        searchPagePadding1.add(searchResultsLabel1);

        searchResultsScrollPane1.setOpaque(false);
        searchResultsScrollPane1.setPreferredSize(new java.awt.Dimension(620, 360));

        reportListPanel.setBackground(new java.awt.Color(204, 204, 204));
        reportListPanel.setMinimumSize(new java.awt.Dimension(920, 46));
        reportListPanel.setPreferredSize(new java.awt.Dimension(580, 400));
        reportListPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));
        searchResultsScrollPane1.setViewportView(reportListPanel);

        searchPagePadding1.add(searchResultsScrollPane1);

        reportPagePanel.add(searchPagePadding1, java.awt.BorderLayout.CENTER);

        regUserTypeContentPanel.setBackground(new java.awt.Color(204, 204, 255));
        regUserTypeContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 0);
        flowLayout7.setAlignOnBaseline(true);
        regUserTypeContentPanel.setLayout(flowLayout7);
        regUserTypeContentPanel.add(filler2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("I'm creating an account as:");
        regUserTypeContentPanel.add(jLabel1);
        regUserTypeContentPanel.add(filler6);

        regClientButton.setBackground(new java.awt.Color(51, 51, 255));
        regClientButton.setForeground(new java.awt.Color(255, 255, 255));
        regClientButton.setText("Client");
        regClientButton.setBorder(null);
        regClientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regClientButton.setPreferredSize(new java.awt.Dimension(73, 23));
        regClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regClientButtonMousePressed(evt);
            }
        });
        regUserTypeContentPanel.add(regClientButton);

        regAdminButton.setBackground(new java.awt.Color(51, 51, 255));
        regAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        regAdminButton.setText("Admin");
        regAdminButton.setBorder(null);
        regAdminButton.setPreferredSize(new java.awt.Dimension(73, 23));
        regAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regAdminButtonMousePressed(evt);
            }
        });
        regAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAdminButtonActionPerformed(evt);
            }
        });
        regUserTypeContentPanel.add(regAdminButton);

        registerContentPanel.setBackground(new java.awt.Color(204, 204, 255));
        registerContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout();
        flowLayout6.setAlignOnBaseline(true);
        registerContentPanel.setLayout(flowLayout6);
        registerContentPanel.add(filler13);

        backToLoginButton.setBackground(new java.awt.Color(255, 255, 255));
        backToLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        backToLoginButton.setText("<- Back to login page");
        backToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backToLoginButtonMousePressed(evt);
            }
        });
        registerContentPanel.add(backToLoginButton);
        registerContentPanel.add(filler8);

        registrationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(51, 51, 51));
        registrationLabel.setText("Register an account");
        registerContentPanel.add(registrationLabel);

        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 12));
        registerContentPanel.add(jSeparator3);

        regFirstNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regFirstNameLabel.setText("First name");
        regFirstNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regFirstNameLabel);

        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField.setForeground(new java.awt.Color(51, 51, 51));
        firstNameField.setText("r");
        firstNameField.setToolTipText("");
        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        firstNameField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(firstNameField);

        regMiddleNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regMiddleNameLabel.setText("Middle name");
        regMiddleNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regMiddleNameLabel);

        middleNameField.setBackground(new java.awt.Color(255, 255, 255));
        middleNameField.setForeground(new java.awt.Color(51, 51, 51));
        middleNameField.setText("k");
        middleNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middleNameField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(middleNameField);

        regLastNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regLastNameLabel.setText("Last name");
        regLastNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regLastNameLabel);

        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameField.setForeground(new java.awt.Color(51, 51, 51));
        lastNameField.setText("flores");
        lastNameField.setActionCommand("<Not Set>");
        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastNameField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(lastNameField);

        regEmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        regEmailLabel.setText("Email address");
        regEmailLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regEmailLabel);

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setForeground(new java.awt.Color(51, 51, 51));
        emailField.setText("rkf@gmail.com");
        emailField.setToolTipText("");
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(emailField);

        regContactNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        regContactNumLabel.setLabelFor(contactNumField);
        regContactNumLabel.setText("Contact number");
        regContactNumLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regContactNumLabel);

        contactNumField.setBackground(new java.awt.Color(255, 255, 255));
        contactNumField.setForeground(new java.awt.Color(51, 51, 51));
        contactNumField.setText("12345");
        contactNumField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contactNumField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(contactNumField);

        regUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regUsernameLabel.setText("Username");
        regUsernameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regUsernameLabel);

        regUsernameField.setBackground(new java.awt.Color(255, 255, 255));
        regUsernameField.setForeground(new java.awt.Color(51, 51, 51));
        regUsernameField.setText("rkf");
        regUsernameField.setToolTipText("");
        regUsernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regUsernameField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(regUsernameField);

        regPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        regPasswordLabel.setText("Password");
        regPasswordLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regPasswordLabel);

        regPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        regPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        regPasswordField.setText("pass");
        regPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regPasswordField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(regPasswordField);

        regConfirmPassLabel.setForeground(new java.awt.Color(51, 51, 51));
        regConfirmPassLabel.setText("Confirm password");
        regConfirmPassLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regConfirmPassLabel);

        confirmPassField.setBackground(new java.awt.Color(255, 255, 255));
        confirmPassField.setForeground(new java.awt.Color(51, 51, 51));
        confirmPassField.setText("pass");
        confirmPassField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmPassField.setPreferredSize(new java.awt.Dimension(150, 20));
        registerContentPanel.add(confirmPassField);
        registerContentPanel.add(filler7);

        confirmPassFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        confirmPassFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        confirmPassFieldErrorLabel.setPreferredSize(new java.awt.Dimension(140, 12));
        registerContentPanel.add(confirmPassFieldErrorLabel);
        registerContentPanel.add(filler9);

        registerSubmitButton.setBackground(new java.awt.Color(51, 51, 255));
        registerSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        registerSubmitButton.setText("Submit");
        registerSubmitButton.setBorder(null);
        registerSubmitButton.setPreferredSize(new java.awt.Dimension(73, 23));
        registerSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerSubmitButtonMousePressed(evt);
            }
        });
        registerContentPanel.add(registerSubmitButton);

        applicationClientPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        applicationClientPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        applicationClientPaddingPanel.setBackground(new java.awt.Color(255, 255, 255));
        applicationClientPaddingPanel.setPreferredSize(new java.awt.Dimension(924, 450));
        applicationClientPaddingPanel.setLayout(new java.awt.CardLayout(10, 10));

        applicationContentPanel.setBackground(new java.awt.Color(255, 255, 255));

        applyForALoanLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        applyForALoanLabel.setForeground(new java.awt.Color(51, 51, 51));
        applyForALoanLabel.setText("Apply for a loan");

        jSeparator7.setPreferredSize(new java.awt.Dimension(900, 3));

        submitApplicationButton.setBackground(new java.awt.Color(51, 51, 255));
        submitApplicationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitApplicationButton.setForeground(new java.awt.Color(255, 255, 255));
        submitApplicationButton.setText("Submit My Application");
        submitApplicationButton.setBorder(null);
        submitApplicationButton.setPreferredSize(new java.awt.Dimension(200, 20));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(850, 308));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(850, 306));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        formPanel.setLayout(flowLayout1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Email address");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Contact Information");

        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Contact number");

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setForeground(new java.awt.Color(51, 51, 51));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(6, 6, 6)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        formPanel.add(jPanel7);

        jScrollPane2.setViewportView(formPanel);

        javax.swing.GroupLayout applicationContentPanelLayout = new javax.swing.GroupLayout(applicationContentPanel);
        applicationContentPanel.setLayout(applicationContentPanelLayout);
        applicationContentPanelLayout.setHorizontalGroup(
            applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applicationContentPanelLayout.createSequentialGroup()
                .addGroup(applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(applicationContentPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitApplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, applicationContentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(applicationContentPanelLayout.createSequentialGroup()
                                .addComponent(applyForALoanLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        applicationContentPanelLayout.setVerticalGroup(
            applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applyForALoanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitApplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        applicationClientPaddingPanel.add(applicationContentPanel, "card6");

        javax.swing.GroupLayout applicationClientPagePanelLayout = new javax.swing.GroupLayout(applicationClientPagePanel);
        applicationClientPagePanel.setLayout(applicationClientPagePanelLayout);
        applicationClientPagePanelLayout.setHorizontalGroup(
            applicationClientPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationClientPagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(applicationClientPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        applicationClientPagePanelLayout.setVerticalGroup(
            applicationClientPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationClientPagePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(applicationClientPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        applicationAdminPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        applicationAdminPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        applicationAdminPaddingPanel.setDividerLocation(550);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pending Applications");

        applicationListPanel.setBackground(new java.awt.Color(204, 204, 204));
        applicationListPanel.setPreferredSize(new java.awt.Dimension(200, 412));

        applicationEntryPanel.setBackground(new java.awt.Color(255, 255, 255));
        applicationEntryPanel.setPreferredSize(new java.awt.Dimension(520, 70));
        applicationEntryPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(430, 60));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Application [289863762]");
        jLabel4.setPreferredSize(new java.awt.Dimension(480, 16));
        jPanel2.add(jLabel4);

        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 5));
        jPanel2.add(jSeparator1);
        jPanel2.add(filler11);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Name");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel2.add(jLabel5);

        applicationEntryPanel.add(jPanel2);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 60));
        applicationEntryPanel.add(jSeparator2);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(60, 23));
        applicationEntryPanel.add(jButton1);

        applicationListPanel.add(applicationEntryPanel);

        jScrollPane3.setViewportView(applicationListPanel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        applicationAdminPaddingPanel.setLeftComponent(jPanel4);

        applicationApprovalPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Application [289863762]");

        jSeparator4.setPreferredSize(new java.awt.Dimension(40, 10));

        javax.swing.GroupLayout applicationApprovalPanelLayout = new javax.swing.GroupLayout(applicationApprovalPanel);
        applicationApprovalPanel.setLayout(applicationApprovalPanelLayout);
        applicationApprovalPanelLayout.setHorizontalGroup(
            applicationApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(applicationApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(applicationApprovalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 263, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        applicationApprovalPanelLayout.setVerticalGroup(
            applicationApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        applicationAdminPaddingPanel.setRightComponent(applicationApprovalPanel);

        javax.swing.GroupLayout applicationAdminPagePanelLayout = new javax.swing.GroupLayout(applicationAdminPagePanel);
        applicationAdminPagePanel.setLayout(applicationAdminPagePanelLayout);
        applicationAdminPagePanelLayout.setHorizontalGroup(
            applicationAdminPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationAdminPagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(applicationAdminPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        applicationAdminPagePanelLayout.setVerticalGroup(
            applicationAdminPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationAdminPagePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(applicationAdminPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        searchPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        searchPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));
        searchPagePanel.setLayout(new java.awt.CardLayout(10, 10));

        searchPagePadding.setBackground(new java.awt.Color(204, 204, 204));
        searchPagePadding.setOpaque(false);

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setForeground(new java.awt.Color(51, 51, 51));
        searchField.setPreferredSize(new java.awt.Dimension(600, 50));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchPagePadding.add(searchField);

        searchSubmitButton.setBackground(new java.awt.Color(153, 153, 153));
        searchSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        searchSubmitButton.setText("Search");
        searchSubmitButton.setBorder(null);
        searchSubmitButton.setIconTextGap(10);
        searchSubmitButton.setPreferredSize(new java.awt.Dimension(100, 50));
        searchSubmitButton.setSelected(true);
        searchSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchSubmitButtonMousePressed(evt);
            }
        });
        searchPagePadding.add(searchSubmitButton);

        searchResultsLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchResultsLabel.setForeground(new java.awt.Color(51, 51, 51));
        searchResultsLabel.setText("Search Results: 0 clients found");
        searchResultsLabel.setPreferredSize(new java.awt.Dimension(900, 24));
        searchPagePadding.add(searchResultsLabel);

        searchResultsScrollPane.setOpaque(false);
        searchResultsScrollPane.setPreferredSize(new java.awt.Dimension(920, 360));

        searchResultsPanel.setBackground(new java.awt.Color(204, 204, 204));
        searchResultsPanel.setMinimumSize(new java.awt.Dimension(920, 46));
        searchResultsPanel.setPreferredSize(new java.awt.Dimension(900, 400));
        searchResultsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));
        searchResultsScrollPane.setViewportView(searchResultsPanel);

        searchPagePadding.add(searchResultsScrollPane);

        searchPagePanel.add(searchPagePadding, "card4");

        aboutPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        aboutPagePanel.setMinimumSize(new java.awt.Dimension(0, 0));
        aboutPagePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        aboutPagePanel.setLayout(new java.awt.CardLayout(240, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("About");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setPreferredSize(new java.awt.Dimension(190, 32));
        jPanel1.add(jLabel24, java.awt.BorderLayout.CENTER);

        aboutPagePanel.add(jPanel1, "card3");

        menuBarPanel.setBackground(new java.awt.Color(51, 51, 255));
        menuBarPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBarPanel.setPreferredSize(new java.awt.Dimension(960, 50));
        menuBarPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 5, 0));

        programNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        programNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        programNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        programNameLabel.setText("LearnLend");
        programNameLabel.setPreferredSize(new java.awt.Dimension(170, 30));
        menuBarPanel.add(programNameLabel);
        menuBarPanel.add(filler1);

        applicationPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(applicationPageToggleButton);
        applicationPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        applicationPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        applicationPageToggleButton.setText("Application");
        applicationPageToggleButton.setBorder(null);
        applicationPageToggleButton.setIconTextGap(5);
        applicationPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        applicationPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                applicationPageToggleButtonItemStateChanged(evt);
            }
        });

        paymentPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(paymentPageToggleButton);
        paymentPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        paymentPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentPageToggleButton.setText("Payment");
        paymentPageToggleButton.setBorder(null);
        paymentPageToggleButton.setIconTextGap(10);
        paymentPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        paymentPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentPageToggleButtonItemStateChanged(evt);
            }
        });

        repaymentPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(repaymentPageToggleButton);
        repaymentPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        repaymentPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        repaymentPageToggleButton.setText("Repayment");
        repaymentPageToggleButton.setBorder(null);
        repaymentPageToggleButton.setIconTextGap(5);
        repaymentPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        repaymentPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                repaymentPageToggleButtonItemStateChanged(evt);
            }
        });

        releasePageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(releasePageToggleButton);
        releasePageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        releasePageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        releasePageToggleButton.setSelected(true);
        releasePageToggleButton.setText("Release");
        releasePageToggleButton.setBorder(null);
        releasePageToggleButton.setIconTextGap(10);
        releasePageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        releasePageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                releasePageToggleButtonItemStateChanged(evt);
            }
        });

        reportPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(reportPageToggleButton);
        reportPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        reportPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        reportPageToggleButton.setText("Report");
        reportPageToggleButton.setBorder(null);
        reportPageToggleButton.setIconTextGap(10);
        reportPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        reportPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reportPageToggleButtonItemStateChanged(evt);
            }
        });

        searchPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(searchPageToggleButton);
        searchPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        searchPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPageToggleButton.setText("Search");
        searchPageToggleButton.setBorder(null);
        searchPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        searchPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchPageToggleButtonItemStateChanged(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(51, 51, 255));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("jButton1");
        logoutButton.setPreferredSize(new java.awt.Dimension(100, 50));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutButtonMousePressed(evt);
            }
        });

        statusPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(statusPageToggleButton);
        statusPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        statusPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        statusPageToggleButton.setText("Status");
        statusPageToggleButton.setBorder(null);
        statusPageToggleButton.setIconTextGap(10);
        statusPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        statusPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusPageToggleButtonItemStateChanged(evt);
            }
        });

        aboutPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(aboutPageToggleButton);
        aboutPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        aboutPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutPageToggleButton.setText("About");
        aboutPageToggleButton.setBorder(null);
        aboutPageToggleButton.setIconTextGap(10);
        aboutPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        aboutPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aboutPageToggleButtonItemStateChanged(evt);
            }
        });

        loginPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        loginPagePanel.setMinimumSize(new java.awt.Dimension(960, 540));
        loginPagePanel.setOpaque(false);
        loginPagePanel.setPreferredSize(new java.awt.Dimension(960, 540));
        loginPagePanel.setLayout(new java.awt.CardLayout(100, 60));

        loginPaddingPanel.setDividerLocation(450);
        loginPaddingPanel.setDividerSize(0);

        loginGraphicsPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        loginGraphicsPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        loginGraphicsPanel.setLayout(new java.awt.BorderLayout());

        loginGraphicLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginGraphicLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginGraphicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginGraphicLabel.setOpaque(true);
        loginGraphicLabel.setPreferredSize(new java.awt.Dimension(330, 330));
        loginGraphicsPanel.add(loginGraphicLabel, java.awt.BorderLayout.CENTER);

        loginPaddingPanel.setLeftComponent(loginGraphicsPanel);

        loginContentPanel.setBackground(new java.awt.Color(204, 204, 255));
        loginContentPanel.setMinimumSize(new java.awt.Dimension(330, 330));
        loginContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 0);
        flowLayout3.setAlignOnBaseline(true);
        loginContentPanel.setLayout(flowLayout3);
        loginContentPanel.add(filler10);

        companyNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        companyNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        companyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameLabel.setText(String.format("<html><body style=\"text-align:center;\">"
            + "%s</body></html>", "LearnLend"));
    companyNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    companyNameLabel.setPreferredSize(new java.awt.Dimension(300, 150));
    loginContentPanel.add(companyNameLabel);

    loginUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
    loginUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginUsernameLabel.setLabelFor(usernameField);
    loginUsernameLabel.setText("Username");
    loginUsernameLabel.setPreferredSize(new java.awt.Dimension(80, 20));
    loginContentPanel.add(loginUsernameLabel);

    usernameField.setBackground(new java.awt.Color(255, 255, 255));
    usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    usernameField.setPreferredSize(new java.awt.Dimension(150, 24));
    loginContentPanel.add(usernameField);
    loginContentPanel.add(filler4);

    usernameFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
    usernameFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
    usernameFieldErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    usernameFieldErrorLabel.setPreferredSize(new java.awt.Dimension(140, 16));
    loginContentPanel.add(usernameFieldErrorLabel);

    passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
    passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    passwordLabel.setLabelFor(passwordField);
    passwordLabel.setText("Password");
    passwordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    passwordLabel.setMinimumSize(new java.awt.Dimension(51, 16));
    passwordLabel.setPreferredSize(new java.awt.Dimension(80, 20));
    loginContentPanel.add(passwordLabel);

    passwordField.setBackground(new java.awt.Color(255, 255, 255));
    passwordField.setToolTipText("");
    passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    passwordField.setPreferredSize(new java.awt.Dimension(150, 24));
    loginContentPanel.add(passwordField);
    loginContentPanel.add(filler5);

    passwordFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
    passwordFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
    passwordFieldErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    passwordFieldErrorLabel.setPreferredSize(new java.awt.Dimension(140, 16));
    passwordFieldErrorLabel.setVerifyInputWhenFocusTarget(false);
    loginContentPanel.add(passwordFieldErrorLabel);
    loginContentPanel.add(filler3);

    loginButton.setBackground(new java.awt.Color(51, 51, 255));
    loginButton.setForeground(new java.awt.Color(255, 255, 255));
    loginButton.setText("Login");
    loginButton.setBorder(null);
    loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    loginButton.setPreferredSize(new java.awt.Dimension(73, 23));
    loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            loginButtonMousePressed(evt);
        }
    });
    loginContentPanel.add(loginButton);

    registerButton.setBackground(new java.awt.Color(51, 51, 255));
    registerButton.setForeground(new java.awt.Color(255, 255, 255));
    registerButton.setText("Register");
    registerButton.setBorder(null);
    registerButton.setPreferredSize(new java.awt.Dimension(73, 23));
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            registerButtonMousePressed(evt);
        }
    });
    loginContentPanel.add(registerButton);

    loginPaddingPanel.setRightComponent(loginContentPanel);

    loginPagePanel.add(loginPaddingPanel, "card3");

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("LearnLend");
    setBounds(new java.awt.Rectangle(0, 0, 960, 540));
    setLocationByPlatform(true);
    setMinimumSize(new java.awt.Dimension(960, 540));
    setResizable(false);

    windowPanel.setPreferredSize(new java.awt.Dimension(960, 540));
    windowPanel.setLayout(new java.awt.BorderLayout());
    getContentPane().add(windowPanel, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        
        usernameFieldErrorLabel.setText("");
        passwordFieldErrorLabel.setText("");
        
        String usernameInput = usernameField.getText();
        String passwordInput = new String(passwordField.getPassword());
        
        Helpers.clearAllFields(loginContentPanel);
                
        for (Admin user : admins) {
            if (user.username.equals(usernameInput) && user.password.equals(passwordInput)) {
                currentAdmin = user;
                initMenu();
                return;
            }
        }
        
        for (Client user : clients) {
            if (user.username.equals(usernameInput) && user.password.equals(passwordInput)) {
                currentClient = user;
                userMode = User.CLIENT;
                initMenu();
                return;
            }
        }
        

        usernameFieldErrorLabel.setText("Username not found");
        passwordFieldErrorLabel.setText("Invalid password");
       
    }//GEN-LAST:event_loginButtonMousePressed

    private void registerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMousePressed
        
        loginPaddingPanel.remove(loginContentPanel);
        loginPaddingPanel.add(regUserTypeContentPanel);        
        loginPaddingPanel.setDividerLocation(450);
        
        revalidate();
        repaint();
        
    }//GEN-LAST:event_registerButtonMousePressed

    private void registerSubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerSubmitButtonMousePressed
        /*
         * DEV NOTE: All fields still do not check if inputs are valid or not
         *           (ex. if name has no numbers, if email address is valid, 
         *           etc.) Please take note of this for future testing
         */
        
        HashMap<String, String> data =  new HashMap<>();
        
        confirmPassFieldErrorLabel.setText("");
        
        // Cancel account creation if any field is empty
        if (Helpers.checkForEmptyFields(registerContentPanel)) {
            return;
        }
        
        /*
         * Checks if both password fields are the same. If not, the program
         * notifies the user about the error and does not proceed with account
         * creation
         */
        String pass1 = new String(regPasswordField.getPassword());
        String pass2 = new String(confirmPassField.getPassword());
        if (pass1.equals(pass2) == false) {
            confirmPassFieldErrorLabel.setText("Password does not match");
            return;
        } 
        
        data.put("first name", firstNameField.getText());
        data.put("middle name", middleNameField.getText());
        data.put("last name", lastNameField.getText());
        data.put("email", emailField.getText());
        data.put("contact number", contactNumField.getText());
        data.put("username", regUsernameField.getText());
        data.put("password", pass1);
        data.put("name", String.format("%s %s %s", data.get("first name"),
                data.get("middle name"), data.get("last name")));
            
        javax.swing.JLabel msg = new javax.swing.JLabel(String.format(
            """
            <html>
              <p>Please confirm your details:</p>
              <p>Username: %s</p>
              <p>Password: %s</p>
              <p>First name: %s</p>
              <p>Middle name: %s</p>
              <p>Last name: %s</p>
              <p>Email: %s</p>
              <p>Contact Number: %s</p>
            </html>
            """,
            data.get("username"), data.get("password").replaceAll(".", "*"),
            data.get("first name"), data.get("middle name"), 
            data.get("last name"), data.get("email"),
            data.get("contact number")
        ));
        
        int confirmation = JOptionPane.showConfirmDialog(null, msg, "Register", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
        
        if (confirmation == 0) {
            if (userMode == User.ADMIN) {
                Admin newAdmin = new Admin(data);
                admins.add(newAdmin);
                newAdmin.saveUserData();
            }
            else {
                Client newClient = new Client(data);
                clients.add(newClient);
                newClient.saveUserData();
            }  
            
            JOptionPane.showMessageDialog(null, "Account successfully created");
            
            Helpers.clearAllFields(registerContentPanel);
            loginPaddingPanel.remove(registerContentPanel);
            loginPaddingPanel.add(loginContentPanel);
            loginPaddingPanel.setDividerLocation(450);
            
            revalidate();
            repaint();            
        }   
    }//GEN-LAST:event_registerSubmitButtonMousePressed

    private void applicationPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_applicationPageToggleButtonItemStateChanged
        if (userMode == User.ADMIN) {
            activePage = applicationAdminPagePanel;
        }
        else if (userMode == User.CLIENT) {
            activePage = applicationClientPagePanel;
        }
        updateMenu();
    }//GEN-LAST:event_applicationPageToggleButtonItemStateChanged

    private void paymentPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentPageToggleButtonItemStateChanged
        activePage = paymentPagePanel;
        updateMenu();
    }//GEN-LAST:event_paymentPageToggleButtonItemStateChanged

    private void statusPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusPageToggleButtonItemStateChanged
        activePage = statusPagePanel;
        updateMenu();
    }//GEN-LAST:event_statusPageToggleButtonItemStateChanged

    private void reportPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reportPageToggleButtonItemStateChanged
        activePage = reportPagePanel;
        updateMenu();
    }//GEN-LAST:event_reportPageToggleButtonItemStateChanged

    private void searchPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchPageToggleButtonItemStateChanged
        activePage = searchPagePanel;
        updateMenu();
    }//GEN-LAST:event_searchPageToggleButtonItemStateChanged

    private void aboutPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aboutPageToggleButtonItemStateChanged
        activePage = aboutPagePanel;
        updateMenu();
    }//GEN-LAST:event_aboutPageToggleButtonItemStateChanged

    private void repaymentPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_repaymentPageToggleButtonItemStateChanged
        activePage = repaymentPagePanel;                
        updateMenu();
    }//GEN-LAST:event_repaymentPageToggleButtonItemStateChanged

    private void regClientButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regClientButtonMousePressed
        userMode = User.CLIENT;
        
        loginPaddingPanel.remove(regUserTypeContentPanel);
        loginPaddingPanel.add(registerContentPanel);
        loginPaddingPanel.setDividerLocation(450);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_regClientButtonMousePressed

    private void regAdminButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regAdminButtonMousePressed
        userMode = User.ADMIN;
        
        loginPaddingPanel.remove(regUserTypeContentPanel);
        loginPaddingPanel.add(registerContentPanel);
        loginPaddingPanel.setDividerLocation(450);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_regAdminButtonMousePressed

    private void regAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regAdminButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void backToLoginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginButtonMousePressed
        Helpers.clearAllFields(registerContentPanel);
        loginPaddingPanel.remove(registerContentPanel);
        loginPaddingPanel.add(loginContentPanel);
        loginPaddingPanel.setDividerLocation(450);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_backToLoginButtonMousePressed

    private void releasePageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_releasePageToggleButtonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_releasePageToggleButtonItemStateChanged

    // This function handles the search module by utilizing regex. Searches through
    // all clients' personal information for a more comprehensive search
    private void searchSubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSubmitButtonMousePressed
        
        int numOfResults = 0;
        
        searchResultsPanel.removeAll(); // Clear previous search results
        
        // Search term length must be more than 2
        if (searchField.getText().length() > 2) {
            // Iterate over all clients and their data
            for (Client c : clients) {
                Pattern pattern = Pattern.compile(searchField.getText());
                String[] client_data = {c.username, c.name, c.email, c.accountNumber,
                    c.contactNumber};

                // Check for matching words in each of client's information and
                // add to search results if the patterns match
                for (String s : client_data) {
                    Matcher matcher = pattern.matcher(s);
                    if (matcher.find()) {
                        searchResultsPanel.add(new SearchResultEntry(c));
                        numOfResults++;
                    }
                }
            }
        }
        
        // Set the UI text according to the number of results
        searchResultsLabel.setText(String.format("Search Results: %d clients found",
                numOfResults));
        
        // Dynamically resize the panel based on the number of results
        searchResultsPanel.setPreferredSize(new java.awt.Dimension(900, 80 * numOfResults));
        
        revalidate();
        repaint();
    }//GEN-LAST:event_searchSubmitButtonMousePressed

    private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMousePressed
        int confirmation = JOptionPane.showConfirmDialog(null, "Confirm logout?", "Logout", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
        
        if (confirmation == 0) {
            currentAdmin = null;
            currentClient = null;
            
            backgroundPanel.removeAll();
            backgroundPanel.add(loginPagePanel);
            
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_logoutButtonMousePressed

    private void searchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchField1ActionPerformed

    private void searchSubmitButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchSubmitButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSubmitButton1MousePressed

    // This function is called to instantiate the menu whether on admin or client
    // mode when login is successful
    private void initMenu() {
        
        windowPanel.removeAll();
        backgroundPanel.removeAll();
        
        if (userMode == User.ADMIN) {
            filler1.setPreferredSize(new java.awt.Dimension(350, 0));
            menuBarPanel.add(applicationPageToggleButton);
            menuBarPanel.add(searchPageToggleButton);
            activePage = applicationAdminPagePanel;
        }
        else if (userMode == User.CLIENT) {
            filler1.setPreferredSize(new java.awt.Dimension(0, 0));
            menuBarPanel.add(applicationPageToggleButton);
            menuBarPanel.add(paymentPageToggleButton);
            menuBarPanel.add(repaymentPageToggleButton);
            menuBarPanel.add(releasePageToggleButton);
            menuBarPanel.add(reportPageToggleButton);
            activePage = applicationClientPagePanel;
        }
        menuBarPanel.add(aboutPageToggleButton);
        menuBarPanel.add(logoutButton);
        
        updateMenu();
    }
    
    private void updateMenu() {
        
        windowPanel.removeAll();
        backgroundPanel.removeAll();
        
        backgroundPanel.add(menuBarPanel);
        backgroundPanel.add(activePage);
        
        windowPanel.add(backgroundPanel);
                    
        revalidate();
        repaint(); 
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {    
                
                GUI window = new GUI();                                
                
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPagePanel;
    private javax.swing.JToggleButton aboutPageToggleButton;
    private javax.swing.JSplitPane applicationAdminPaddingPanel;
    private javax.swing.JPanel applicationAdminPagePanel;
    private javax.swing.JPanel applicationApprovalPanel;
    private javax.swing.JPanel applicationClientPaddingPanel;
    private javax.swing.JPanel applicationClientPagePanel;
    private javax.swing.JPanel applicationContentPanel;
    private javax.swing.JPanel applicationEntryPanel;
    private javax.swing.JPanel applicationListPanel;
    private javax.swing.JToggleButton applicationPageToggleButton;
    private javax.swing.JLabel applyForALoanLabel;
    private javax.swing.JButton backToLoginButton;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPassFieldErrorLabel;
    private javax.swing.JTextField contactNumField;
    private javax.swing.JTextField emailField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginContentPanel;
    private javax.swing.JLabel loginGraphicLabel;
    private javax.swing.JPanel loginGraphicsPanel;
    private javax.swing.JSplitPane loginPaddingPanel;
    private javax.swing.JPanel loginPagePanel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.ButtonGroup menuButtonGroup;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordFieldErrorLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel paymentPagePanel;
    private javax.swing.JToggleButton paymentPageToggleButton;
    private javax.swing.JLabel programNameLabel;
    private javax.swing.JButton regAdminButton;
    private javax.swing.JButton regClientButton;
    private javax.swing.JLabel regConfirmPassLabel;
    private javax.swing.JLabel regContactNumLabel;
    private javax.swing.JLabel regEmailLabel;
    private javax.swing.JLabel regFirstNameLabel;
    private javax.swing.JLabel regLastNameLabel;
    private javax.swing.JLabel regMiddleNameLabel;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JLabel regPasswordLabel;
    private javax.swing.JPanel regUserTypeContentPanel;
    private javax.swing.JTextField regUsernameField;
    private javax.swing.JLabel regUsernameLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerContentPanel;
    private javax.swing.JButton registerSubmitButton;
    private javax.swing.JLabel registrationLabel;
    private javax.swing.JToggleButton releasePageToggleButton;
    private javax.swing.JPanel repaymentPagePanel;
    private javax.swing.JToggleButton repaymentPageToggleButton;
    private javax.swing.JPanel reportListPanel;
    private javax.swing.JPanel reportPagePanel;
    private javax.swing.JToggleButton reportPageToggleButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField searchField1;
    private javax.swing.JPanel searchPagePadding;
    private javax.swing.JPanel searchPagePadding1;
    private javax.swing.JPanel searchPagePanel;
    private javax.swing.JToggleButton searchPageToggleButton;
    private javax.swing.JLabel searchResultsLabel;
    private javax.swing.JLabel searchResultsLabel1;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JScrollPane searchResultsScrollPane;
    private javax.swing.JScrollPane searchResultsScrollPane1;
    private javax.swing.JButton searchSubmitButton;
    private javax.swing.JButton searchSubmitButton1;
    private javax.swing.JPanel statusPagePanel;
    private javax.swing.JToggleButton statusPageToggleButton;
    private javax.swing.JButton submitApplicationButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameFieldErrorLabel;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables

    private JPanelBackground backgroundPanel;
}

class JPanelBackground extends javax.swing.JPanel {

    private java.awt.Image backgroundImage;

    public JPanelBackground(String filename) {
        try {
            backgroundImage = javax.imageio.ImageIO.read(new java.io.File(filename));
        }
        catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
    
    public JPanelBackground(java.awt.Color c) {
        setBackground(c);
    }

    @Override
    public void paintComponent(java.awt.Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(backgroundImage, 0, 0, this);
    }
  
}

class SearchResultEntry extends javax.swing.JPanel {
    
    javax.swing.JPanel userDetailsPanel = new javax.swing.JPanel();
    javax.swing.JLabel usernameLabel = new javax.swing.JLabel();
    javax.swing.JLabel nameLabel = new javax.swing.JLabel();
    javax.swing.JLabel emailLabel = new javax.swing.JLabel();
    javax.swing.JLabel accountNumberLabel = new javax.swing.JLabel();
    javax.swing.JLabel contactNumberLabel = new javax.swing.JLabel();
    javax.swing.JLabel userTypeLabel = new javax.swing.JLabel();
    javax.swing.JSeparator vertSeparator = new javax.swing.JSeparator();
    javax.swing.JButton btn = new javax.swing.JButton();
    Client user = null;
    
    public SearchResultEntry(Client c) {
        user = c;
        
        setPreferredSize(new java.awt.Dimension(880, 70));
        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        
        userDetailsPanel.setOpaque(false);
        userDetailsPanel.setPreferredSize(new java.awt.Dimension(800, 60));
        userDetailsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        usernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel.setText("Username: " + user.username);
        usernameLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(usernameLabel);

        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("Name: " + user.name);
        nameLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(nameLabel);

        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email: " + user.email);
        emailLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(emailLabel);

        accountNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        accountNumberLabel.setText("Account Number: " + user.accountNumber);
        accountNumberLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(accountNumberLabel);

        contactNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        contactNumberLabel.setText("Contact Number: " + user.contactNumber);
        contactNumberLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(contactNumberLabel);
        add(userDetailsPanel);
        
        userTypeLabel.setForeground(new java.awt.Color(51, 51, 51));
        if (user.accountType == User.ADMIN) {
            userTypeLabel.setText("Account Type: Admin");
        }
        else if (user.accountType == User.CLIENT) {
            userTypeLabel.setText("Account Type: Client");
        }
        userTypeLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        userDetailsPanel.add(userTypeLabel);
        
        vertSeparator.setForeground(new java.awt.Color(204, 204, 204));
        vertSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vertSeparator.setPreferredSize(new java.awt.Dimension(5, 50));
        add(vertSeparator);
        
        btn.setPreferredSize(new java.awt.Dimension(40, 40));
        btn.setBorder(null);
        btn.setOpaque(false);
        btn.setIcon(Helpers.resizeIcon("detailsArrow", 40, 40));
        btn.setText("Choose file");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
        });
        add(btn);
    }    
    
    private void btnMousePressed(java.awt.event.MouseEvent evt) {
        
        javax.swing.JOptionPane userDetailsPane = new javax.swing.JOptionPane();
        
        userDetailsPane.showMessageDialog(null, String.format( 
            """
            <html>
              <h3>USER DETAILS:</h3>
              <p>Username: %s</p>
              <p>Password: %s</p>
              <p>Account Type: %s</p>
              <br>
              <h3>PERSONAL INFORMATION:</h3>
              <p>First name: %s</p>
              <p>Middle name: %s</p>
              <p>Last name: %s</p>
              <br>
              <h3>CONTACT INFORMATION:</h3>
              <p>Email: %s</p>
              <p>Contact Number: %s</p>
            </html>                                   
            """,  
            user.username, user.getFormattedPassword(),
            user.getAccountTypeInWords(), user.firstName, user.middleName, 
            user.lastName, user.email, user.contactNumber), 
            "User details", JOptionPane.INFORMATION_MESSAGE, null);
    }
           
}
    
class ImageFileChooser extends javax.swing.JPanel {
    
    javax.swing.JButton btn = new javax.swing.JButton();
    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    javax.swing.JLabel fileLabel = new javax.swing.JLabel("No file chosen");
    java.io.File file;
    java.awt.Image img;
    
    public ImageFileChooser() {
        
        btn.setBackground(new java.awt.Color(152, 152, 152));
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setPreferredSize(new java.awt.Dimension(80, 20));
        btn.setBorder(null);
        btn.setText("Choose file");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
        });
        
        fileLabel.setForeground(new java.awt.Color(0, 0, 0));
        
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Choose file");        
        fc.addChoosableFileFilter(new 
            javax.swing.filechooser.FileNameExtensionFilter(
            "Image Files (.jpg, .png)", "jpg", "png"));        
        fc.setPreferredSize(new java.awt.Dimension(500, 400));
        
        setPreferredSize(new java.awt.Dimension(200, 24));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
        setOpaque(false);
        add(btn);
        add(fileLabel);
    }
    
    private void btnMousePressed(java.awt.event.MouseEvent evt) {                                      
        int returnVal = fc.showOpenDialog(null);
        
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                
                try {
                    img = javax.imageio.ImageIO.read(file);
                    
                    // TODO: File handling
                } 
                catch (java.io.IOException e) {
                    e.printStackTrace();
                }
                
                fileLabel.setText(file.getName());
        }
    }
    
    public java.awt.Image getImage() {
        return img;
    }
    
    public String getFileDirectory() {
        return file.getAbsolutePath();
    }
    
}

class TransactionEntryPanel extends javax.swing.JPanel {
    
    javax.swing.JPanel panelContent = new javax.swing.JPanel();
    javax.swing.JLabel dateTimeLabel = new javax.swing.JLabel();
    javax.swing.JLabel amountLabel = new javax.swing.JLabel();
    javax.swing.JLabel refIDLabel = new javax.swing.JLabel();

    public TransactionEntryPanel(String dateTime, String amount,
        String refID) {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(580, 60));
        setLayout(new java.awt.CardLayout(5, 5));

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setPreferredSize(new java.awt.Dimension(580, 60));
        panelContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        dateTimeLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateTimeLabel.setText(dateTime);
        dateTimeLabel.setPreferredSize(new java.awt.Dimension(190, 16));
        panelContent.add(dateTimeLabel);
       
        insertSeparator();

        amountLabel.setForeground(new java.awt.Color(0, 0, 0));
        amountLabel.setText(amount);
        amountLabel.setPreferredSize(new java.awt.Dimension(160, 16));
        panelContent.add(amountLabel);
        
        insertSeparator();

        refIDLabel.setForeground(new java.awt.Color(0, 0, 0));
        refIDLabel.setText(refID);
        refIDLabel.setPreferredSize(new java.awt.Dimension(160, 16));
        panelContent.add(refIDLabel);

        add(panelContent, "card2");
    }
    
    private void insertSeparator() {
        javax.swing.JSeparator vertSeparator = new javax.swing.JSeparator();
        
        vertSeparator.setForeground(new java.awt.Color(204, 204, 204));
        vertSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vertSeparator.setMinimumSize(new java.awt.Dimension(10, 100));
        vertSeparator.setPreferredSize(new java.awt.Dimension(5, 50));
        
        panelContent.add(vertSeparator);
    }

}