package com.ite012.group4.lms;    

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;

public class GUI extends javax.swing.JFrame {

    ArrayList<User> users = new ArrayList();
    private User currentUser;
    private int userType = 0;
    private javax.swing.JPanel activePage = new javax.swing.JPanel();
    
    
    public GUI() {
        initComponents();       

        Helpers.loadIcons();
        
        loginGraphicLabel.setIcon(Helpers.resizeIcon("loginGraphicsIcon", 330, 330));
        menuPageToggleButton.setIcon(Helpers.resizeIcon("menuIcon", 15, 15));
        applicationPageToggleButton.setIcon(Helpers.resizeIcon("applicationIcon", 15, 15));
        statusPageToggleButton.setIcon(Helpers.resizeIcon("statusIcon", 15, 15));  
        paymentPageToggleButton.setIcon(Helpers.resizeIcon("paymentIcon", 15, 15));       
        repaymentPageToggleButton.setIcon(Helpers.resizeIcon("repaymentIcon", 15, 15));
        searchPageToggleButton.setIcon(Helpers.resizeIcon("searchIcon", 15, 15));
        searchSubmitButton.setIcon(Helpers.resizeIcon("searchIcon", 20, 20));
        reportPageToggleButton.setIcon(Helpers.resizeIcon("reportIcon", 15, 15));
        aboutPageToggleButton.setIcon(Helpers.resizeIcon("aboutIcon", 15, 15));

        ImageFileChooser imageChooser1 = new ImageFileChooser();
        formPanel.add(imageChooser1);
        
        searchResultsPanel.add(new searchResultEntry());
        
        //Admin.loadAllUsers(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentPagePanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        statusPagePanel = new javax.swing.JPanel();
        repaymentPagePanel = new javax.swing.JPanel();
        reportPagePanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        aboutPagePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        registerContentPanel = new javax.swing.JPanel();
        backToLoginButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 5), new java.awt.Dimension(150, 5), new java.awt.Dimension(30, 5));
        registrationLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        regFirstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        regMiddleNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        regLastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        regEmailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        regContactNumLabel = new javax.swing.JLabel();
        contactNumField = new javax.swing.JTextField();
        regUsernameLabel = new javax.swing.JLabel();
        regUsernameField = new javax.swing.JTextField();
        regPasswordLabel = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        regConfirmPassLabel = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(100, 0));
        confirmPassFieldErrorLabel = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(320, 0), new java.awt.Dimension(320, 0), new java.awt.Dimension(320, 0));
        registerSubmitButton = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();
        menuButtonGroup = new javax.swing.ButtonGroup();
        menuPagePanel = new javax.swing.JPanel();
        dashboardContent = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblAccountInfo = new javax.swing.JLabel();
        btnUpdateAccountInfo = new javax.swing.JButton();
        dashAccountNameLabel = new javax.swing.JLabel();
        dashEmailLabel = new javax.swing.JLabel();
        dashAccountNumLabel = new javax.swing.JLabel();
        dashContactNumLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        regUserTypeContentPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 50), new java.awt.Dimension(200, 120), new java.awt.Dimension(1, 50));
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(300, 20), new java.awt.Dimension(80, 0));
        regClientButton = new javax.swing.JButton();
        regAdminButton = new javax.swing.JButton();
        applicationPagePanel = new javax.swing.JPanel();
        applicationPaddingPanel = new javax.swing.JPanel();
        applicationContentPanel = new javax.swing.JPanel();
        applyForALoanLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        submitApplicationButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        searchPagePanel = new javax.swing.JPanel();
        searchPagePadding = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchSubmitButton = new javax.swing.JButton();
        searchResultsLabel = new javax.swing.JLabel();
        searchResultsScrollPane = new javax.swing.JScrollPane();
        searchResultsPanel = new javax.swing.JPanel();
        menuBarPanel = new javax.swing.JPanel();
        programNameLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        menuPageToggleButton = new javax.swing.JToggleButton();
        applicationPageToggleButton = new javax.swing.JToggleButton();
        paymentPageToggleButton = new javax.swing.JToggleButton();
        repaymentPageToggleButton = new javax.swing.JToggleButton();
        reportPageToggleButton = new javax.swing.JToggleButton();
        aboutPageToggleButton = new javax.swing.JToggleButton();
        searchPageToggleButton = new javax.swing.JToggleButton();
        statusPageToggleButton = new javax.swing.JToggleButton();
        windowPanel = new javax.swing.JPanel();
        loginPagePanel = new javax.swing.JPanel();
        loginPaddingPanel = new javax.swing.JPanel();
        loginGraphicsPanel = new javax.swing.JPanel();
        loginGraphicLabel = new javax.swing.JLabel();
        loginContentPanel = new javax.swing.JPanel();
        companyNameLabel = new javax.swing.JLabel();
        loginUsernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(80, 0));
        usernameFieldErrorLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(80, 0));
        passwordFieldErrorLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(300, 12), new java.awt.Dimension(200, 0));
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        paymentPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        paymentPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Payment Window");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout paymentPagePanelLayout = new javax.swing.GroupLayout(paymentPagePanel);
        paymentPagePanel.setLayout(paymentPagePanelLayout);
        paymentPagePanelLayout.setHorizontalGroup(
            paymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        paymentPagePanelLayout.setVerticalGroup(
            paymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout statusPagePanelLayout = new javax.swing.GroupLayout(statusPagePanel);
        statusPagePanel.setLayout(statusPagePanelLayout);
        statusPagePanelLayout.setHorizontalGroup(
            statusPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        statusPagePanelLayout.setVerticalGroup(
            statusPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout repaymentPagePanelLayout = new javax.swing.GroupLayout(repaymentPagePanel);
        repaymentPagePanel.setLayout(repaymentPagePanelLayout);
        repaymentPagePanelLayout.setHorizontalGroup(
            repaymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        repaymentPagePanelLayout.setVerticalGroup(
            repaymentPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        reportPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        reportPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Report Window");

        javax.swing.GroupLayout reportPagePanelLayout = new javax.swing.GroupLayout(reportPagePanel);
        reportPagePanel.setLayout(reportPagePanelLayout);
        reportPagePanelLayout.setHorizontalGroup(
            reportPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportPagePanelLayout.setVerticalGroup(
            reportPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        aboutPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        aboutPagePanel.setMinimumSize(new java.awt.Dimension(0, 0));
        aboutPagePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        aboutPagePanel.setLayout(new java.awt.CardLayout(240, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("About");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setPreferredSize(new java.awt.Dimension(190, 32));
        jPanel1.add(jLabel24, java.awt.BorderLayout.CENTER);

        aboutPagePanel.add(jPanel1, "card3");

        registerContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout();
        flowLayout6.setAlignOnBaseline(true);
        registerContentPanel.setLayout(flowLayout6);

        backToLoginButton.setBackground(new java.awt.Color(255, 255, 255));
        backToLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        backToLoginButton.setText("<- Back to login page");
        backToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backToLoginButtonMousePressed(evt);
            }
        });
        registerContentPanel.add(backToLoginButton);
        registerContentPanel.add(filler8);

        registrationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrationLabel.setForeground(new java.awt.Color(51, 51, 51));
        registrationLabel.setText("Register an account");
        registerContentPanel.add(registrationLabel);

        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 12));
        registerContentPanel.add(jSeparator3);

        regFirstNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regFirstNameLabel.setText("First name");
        regFirstNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regFirstNameLabel);

        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField.setForeground(new java.awt.Color(51, 51, 51));
        firstNameField.setText("r");
        firstNameField.setToolTipText("");
        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        firstNameField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(firstNameField);

        regMiddleNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regMiddleNameLabel.setText("Middle name");
        regMiddleNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regMiddleNameLabel);

        middleNameField.setBackground(new java.awt.Color(255, 255, 255));
        middleNameField.setForeground(new java.awt.Color(51, 51, 51));
        middleNameField.setText("k");
        middleNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middleNameField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(middleNameField);

        regLastNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regLastNameLabel.setText("Last name");
        regLastNameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regLastNameLabel);

        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameField.setForeground(new java.awt.Color(51, 51, 51));
        lastNameField.setText("flores");
        lastNameField.setActionCommand("<Not Set>");
        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastNameField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(lastNameField);

        regEmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        regEmailLabel.setText("Email address");
        regEmailLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regEmailLabel);

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setForeground(new java.awt.Color(51, 51, 51));
        emailField.setText("rkf@gmail.com");
        emailField.setToolTipText("");
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(emailField);

        regContactNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        regContactNumLabel.setLabelFor(contactNumField);
        regContactNumLabel.setText("Contact number");
        regContactNumLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regContactNumLabel);

        contactNumField.setBackground(new java.awt.Color(255, 255, 255));
        contactNumField.setForeground(new java.awt.Color(51, 51, 51));
        contactNumField.setText("12345");
        contactNumField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contactNumField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(contactNumField);

        regUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        regUsernameLabel.setText("Username");
        regUsernameLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regUsernameLabel);

        regUsernameField.setBackground(new java.awt.Color(255, 255, 255));
        regUsernameField.setForeground(new java.awt.Color(51, 51, 51));
        regUsernameField.setText("rkf");
        regUsernameField.setToolTipText("");
        regUsernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regUsernameField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(regUsernameField);

        regPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        regPasswordLabel.setText("Password");
        regPasswordLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regPasswordLabel);

        regPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        regPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        regPasswordField.setText("pass");
        regPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regPasswordField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(regPasswordField);

        regConfirmPassLabel.setForeground(new java.awt.Color(51, 51, 51));
        regConfirmPassLabel.setText("Confirm password");
        regConfirmPassLabel.setPreferredSize(new java.awt.Dimension(110, 16));
        registerContentPanel.add(regConfirmPassLabel);

        confirmPassField.setBackground(new java.awt.Color(255, 255, 255));
        confirmPassField.setForeground(new java.awt.Color(51, 51, 51));
        confirmPassField.setText("pass");
        confirmPassField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmPassField.setPreferredSize(new java.awt.Dimension(180, 20));
        registerContentPanel.add(confirmPassField);
        registerContentPanel.add(filler7);

        confirmPassFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        confirmPassFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        confirmPassFieldErrorLabel.setPreferredSize(new java.awt.Dimension(120, 12));
        registerContentPanel.add(confirmPassFieldErrorLabel);
        registerContentPanel.add(filler9);

        registerSubmitButton.setBackground(new java.awt.Color(51, 51, 255));
        registerSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        registerSubmitButton.setText("Submit");
        registerSubmitButton.setBorder(null);
        registerSubmitButton.setPreferredSize(new java.awt.Dimension(73, 23));
        registerSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerSubmitButtonMousePressed(evt);
            }
        });
        registerContentPanel.add(registerSubmitButton);

        backgroundPanel.setBackground(new java.awt.Color(204, 204, 204));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(960, 490));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        backgroundPanel.setLayout(flowLayout2);

        menuPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        menuPagePanel.setMinimumSize(new java.awt.Dimension(40, 20));
        menuPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));
        menuPagePanel.setLayout(new java.awt.CardLayout(20, 10));

        dashboardContent.setBackground(new java.awt.Color(255, 255, 255));
        dashboardContent.setPreferredSize(new java.awt.Dimension(0, 0));

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(51, 51, 51));
        lblDashboard.setText("Dashboard");

        lblAccountInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAccountInfo.setForeground(new java.awt.Color(51, 51, 51));
        lblAccountInfo.setText("Account Info");

        btnUpdateAccountInfo.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateAccountInfo.setForeground(new java.awt.Color(102, 153, 255));
        btnUpdateAccountInfo.setText("Update");
        btnUpdateAccountInfo.setBorder(null);
        btnUpdateAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAccountInfoActionPerformed(evt);
            }
        });

        dashAccountNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashAccountNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        dashAccountNameLabel.setText("Client name ");

        dashEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashEmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        dashEmailLabel.setText("Email");

        dashAccountNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashAccountNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        dashAccountNumLabel.setText("Account number");

        dashContactNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashContactNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        dashContactNumLabel.setText("Contact number");

        javax.swing.GroupLayout dashboardContentLayout = new javax.swing.GroupLayout(dashboardContent);
        dashboardContent.setLayout(dashboardContentLayout);
        dashboardContentLayout.setHorizontalGroup(
            dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDashboard)
                    .addGroup(dashboardContentLayout.createSequentialGroup()
                        .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashAccountNameLabel)
                            .addComponent(dashAccountNumLabel))
                        .addGap(65, 65, 65)
                        .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashEmailLabel)
                            .addComponent(dashContactNumLabel)))
                    .addGroup(dashboardContentLayout.createSequentialGroup()
                        .addComponent(lblAccountInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateAccountInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardContentLayout.setVerticalGroup(
            dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccountInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashAccountNameLabel)
                    .addComponent(dashEmailLabel))
                .addGap(5, 5, 5)
                .addGroup(dashboardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashContactNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashAccountNumLabel))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        menuPagePanel.add(dashboardContent, "card2");

        regUserTypeContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        regUserTypeContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 0);
        flowLayout7.setAlignOnBaseline(true);
        regUserTypeContentPanel.setLayout(flowLayout7);
        regUserTypeContentPanel.add(filler2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("I'm creating an account as:");
        regUserTypeContentPanel.add(jLabel1);
        regUserTypeContentPanel.add(filler6);

        regClientButton.setBackground(new java.awt.Color(51, 51, 255));
        regClientButton.setForeground(new java.awt.Color(255, 255, 255));
        regClientButton.setText("Client");
        regClientButton.setBorder(null);
        regClientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regClientButton.setPreferredSize(new java.awt.Dimension(73, 23));
        regClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regClientButtonMousePressed(evt);
            }
        });
        regUserTypeContentPanel.add(regClientButton);

        regAdminButton.setBackground(new java.awt.Color(51, 51, 255));
        regAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        regAdminButton.setText("Admin");
        regAdminButton.setBorder(null);
        regAdminButton.setPreferredSize(new java.awt.Dimension(73, 23));
        regAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regAdminButtonMousePressed(evt);
            }
        });
        regAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAdminButtonActionPerformed(evt);
            }
        });
        regUserTypeContentPanel.add(regAdminButton);

        applicationPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        applicationPagePanel.setPreferredSize(new java.awt.Dimension(960, 490));

        applicationPaddingPanel.setBackground(new java.awt.Color(255, 255, 255));
        applicationPaddingPanel.setPreferredSize(new java.awt.Dimension(924, 450));
        applicationPaddingPanel.setLayout(new java.awt.CardLayout(10, 10));

        applicationContentPanel.setBackground(new java.awt.Color(255, 255, 255));

        applyForALoanLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        applyForALoanLabel.setForeground(new java.awt.Color(51, 51, 51));
        applyForALoanLabel.setText("Apply for a loan");

        jSeparator5.setPreferredSize(new java.awt.Dimension(900, 3));

        submitApplicationButton.setBackground(new java.awt.Color(51, 51, 255));
        submitApplicationButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitApplicationButton.setForeground(new java.awt.Color(255, 255, 255));
        submitApplicationButton.setText("Submit My Application");
        submitApplicationButton.setBorder(null);
        submitApplicationButton.setPreferredSize(new java.awt.Dimension(200, 20));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(850, 308));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setPreferredSize(new java.awt.Dimension(850, 306));
        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout5.setAlignOnBaseline(true);
        formPanel.setLayout(flowLayout5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Email address");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Contact Information");

        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Contact number");

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setForeground(new java.awt.Color(51, 51, 51));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(6, 6, 6)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        formPanel.add(jPanel6);

        jScrollPane1.setViewportView(formPanel);

        javax.swing.GroupLayout applicationContentPanelLayout = new javax.swing.GroupLayout(applicationContentPanel);
        applicationContentPanel.setLayout(applicationContentPanelLayout);
        applicationContentPanelLayout.setHorizontalGroup(
            applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applicationContentPanelLayout.createSequentialGroup()
                .addGroup(applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(applicationContentPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitApplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, applicationContentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(applicationContentPanelLayout.createSequentialGroup()
                                .addComponent(applyForALoanLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        applicationContentPanelLayout.setVerticalGroup(
            applicationContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applyForALoanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitApplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        applicationPaddingPanel.add(applicationContentPanel, "card6");

        javax.swing.GroupLayout applicationPagePanelLayout = new javax.swing.GroupLayout(applicationPagePanel);
        applicationPagePanel.setLayout(applicationPagePanelLayout);
        applicationPagePanelLayout.setHorizontalGroup(
            applicationPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(applicationPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        applicationPagePanelLayout.setVerticalGroup(
            applicationPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPagePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(applicationPaddingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        searchPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        searchPagePanel.setLayout(new java.awt.CardLayout(10, 10));

        searchPagePadding.setBackground(new java.awt.Color(204, 204, 204));
        searchPagePadding.setOpaque(false);

        searchField.setBackground(new java.awt.Color(255, 255, 255));
        searchField.setForeground(new java.awt.Color(51, 51, 51));
        searchField.setPreferredSize(new java.awt.Dimension(600, 50));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchPagePadding.add(searchField);

        searchSubmitButton.setBackground(new java.awt.Color(153, 153, 153));
        searchSubmitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        searchSubmitButton.setText("Search");
        searchSubmitButton.setBorder(null);
        searchSubmitButton.setIconTextGap(10);
        searchSubmitButton.setPreferredSize(new java.awt.Dimension(100, 50));
        searchSubmitButton.setSelected(true);
        searchSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSubmitButtonActionPerformed(evt);
            }
        });
        searchPagePadding.add(searchSubmitButton);

        searchResultsLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        searchResultsLabel.setForeground(new java.awt.Color(51, 51, 51));
        searchResultsLabel.setText("Search Results: 0 clients found");
        searchResultsLabel.setPreferredSize(new java.awt.Dimension(900, 24));
        searchPagePadding.add(searchResultsLabel);

        searchResultsScrollPane.setOpaque(false);
        searchResultsScrollPane.setPreferredSize(new java.awt.Dimension(920, 360));

        searchResultsPanel.setBackground(new java.awt.Color(204, 204, 204));
        searchResultsPanel.setMinimumSize(new java.awt.Dimension(920, 46));
        searchResultsPanel.setPreferredSize(new java.awt.Dimension(900, 400));
        searchResultsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));
        searchResultsScrollPane.setViewportView(searchResultsPanel);

        searchPagePadding.add(searchResultsScrollPane);

        searchPagePanel.add(searchPagePadding, "card4");

        menuBarPanel.setBackground(new java.awt.Color(51, 51, 255));
        menuBarPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBarPanel.setPreferredSize(new java.awt.Dimension(960, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        menuBarPanel.setLayout(flowLayout1);

        programNameLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        programNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        programNameLabel.setText("Program Name");
        menuBarPanel.add(programNameLabel);
        menuBarPanel.add(filler1);

        menuPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(menuPageToggleButton);
        menuPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        menuPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        menuPageToggleButton.setSelected(true);
        menuPageToggleButton.setText("Menu");
        menuPageToggleButton.setBorder(null);
        menuPageToggleButton.setIconTextGap(10);
        menuPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        menuPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(menuPageToggleButton);

        applicationPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(applicationPageToggleButton);
        applicationPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        applicationPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        applicationPageToggleButton.setText("Application");
        applicationPageToggleButton.setBorder(null);
        applicationPageToggleButton.setIconTextGap(5);
        applicationPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        applicationPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                applicationPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(applicationPageToggleButton);

        paymentPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(paymentPageToggleButton);
        paymentPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        paymentPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentPageToggleButton.setText("Payment");
        paymentPageToggleButton.setBorder(null);
        paymentPageToggleButton.setIconTextGap(10);
        paymentPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        paymentPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(paymentPageToggleButton);

        repaymentPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(repaymentPageToggleButton);
        repaymentPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        repaymentPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        repaymentPageToggleButton.setText("Repayment");
        repaymentPageToggleButton.setBorder(null);
        repaymentPageToggleButton.setIconTextGap(5);
        repaymentPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        repaymentPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                repaymentPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(repaymentPageToggleButton);

        reportPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(reportPageToggleButton);
        reportPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        reportPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        reportPageToggleButton.setText("Report");
        reportPageToggleButton.setBorder(null);
        reportPageToggleButton.setIconTextGap(10);
        reportPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        reportPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reportPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(reportPageToggleButton);

        aboutPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(aboutPageToggleButton);
        aboutPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        aboutPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutPageToggleButton.setText("About");
        aboutPageToggleButton.setBorder(null);
        aboutPageToggleButton.setIconTextGap(10);
        aboutPageToggleButton.setPreferredSize(new java.awt.Dimension(110, 50));
        aboutPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                aboutPageToggleButtonItemStateChanged(evt);
            }
        });
        menuBarPanel.add(aboutPageToggleButton);

        searchPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(searchPageToggleButton);
        searchPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPageToggleButton.setText("Search");
        searchPageToggleButton.setBorder(null);
        searchPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        searchPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchPageToggleButtonItemStateChanged(evt);
            }
        });

        statusPageToggleButton.setBackground(new java.awt.Color(51, 51, 255));
        menuButtonGroup.add(statusPageToggleButton);
        statusPageToggleButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        statusPageToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        statusPageToggleButton.setText("Status");
        statusPageToggleButton.setBorder(null);
        statusPageToggleButton.setIconTextGap(10);
        statusPageToggleButton.setPreferredSize(new java.awt.Dimension(100, 50));
        statusPageToggleButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusPageToggleButtonItemStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Management System");
        setBounds(new java.awt.Rectangle(0, 0, 960, 540));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        windowPanel.setPreferredSize(new java.awt.Dimension(960, 540));
        windowPanel.setLayout(new java.awt.BorderLayout());

        loginPagePanel.setBackground(new java.awt.Color(204, 204, 204));
        loginPagePanel.setMinimumSize(new java.awt.Dimension(960, 540));
        loginPagePanel.setPreferredSize(new java.awt.Dimension(960, 540));
        loginPagePanel.setLayout(new java.awt.CardLayout(100, 60));

        loginPaddingPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPaddingPanel.setPreferredSize(new java.awt.Dimension(800, 400));
        loginPaddingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 50));

        loginGraphicsPanel.setMinimumSize(new java.awt.Dimension(500, 500));
        loginGraphicsPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        loginGraphicsPanel.setLayout(new java.awt.BorderLayout());

        loginGraphicLabel.setBackground(new java.awt.Color(255, 255, 255));
        loginGraphicLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginGraphicLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginGraphicLabel.setOpaque(true);
        loginGraphicLabel.setPreferredSize(new java.awt.Dimension(330, 330));
        loginGraphicsPanel.add(loginGraphicLabel, java.awt.BorderLayout.PAGE_END);

        loginPaddingPanel.add(loginGraphicsPanel);

        loginContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginContentPanel.setMinimumSize(new java.awt.Dimension(330, 330));
        loginContentPanel.setPreferredSize(new java.awt.Dimension(330, 330));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 0);
        flowLayout3.setAlignOnBaseline(true);
        loginContentPanel.setLayout(flowLayout3);

        companyNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        companyNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        companyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companyNameLabel.setText(String.format("<html><body style=\"text-align:center;\">"
            + "%s</body></html>", "Digital Loan Management System"));
    companyNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    companyNameLabel.setPreferredSize(new java.awt.Dimension(300, 150));
    loginContentPanel.add(companyNameLabel);

    loginUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
    loginUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    loginUsernameLabel.setLabelFor(usernameField);
    loginUsernameLabel.setText("Username");
    loginUsernameLabel.setPreferredSize(new java.awt.Dimension(80, 20));
    loginContentPanel.add(loginUsernameLabel);

    usernameField.setBackground(new java.awt.Color(255, 255, 255));
    usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    usernameField.setPreferredSize(new java.awt.Dimension(150, 24));
    loginContentPanel.add(usernameField);
    loginContentPanel.add(filler4);

    usernameFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
    usernameFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
    usernameFieldErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    usernameFieldErrorLabel.setPreferredSize(new java.awt.Dimension(140, 16));
    loginContentPanel.add(usernameFieldErrorLabel);

    passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
    passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    passwordLabel.setLabelFor(passwordField);
    passwordLabel.setText("Password");
    passwordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    passwordLabel.setMinimumSize(new java.awt.Dimension(51, 16));
    passwordLabel.setPreferredSize(new java.awt.Dimension(80, 20));
    loginContentPanel.add(passwordLabel);

    passwordField.setBackground(new java.awt.Color(255, 255, 255));
    passwordField.setToolTipText("");
    passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    passwordField.setPreferredSize(new java.awt.Dimension(150, 24));
    loginContentPanel.add(passwordField);
    loginContentPanel.add(filler5);

    passwordFieldErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
    passwordFieldErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
    passwordFieldErrorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    passwordFieldErrorLabel.setPreferredSize(new java.awt.Dimension(140, 16));
    passwordFieldErrorLabel.setVerifyInputWhenFocusTarget(false);
    loginContentPanel.add(passwordFieldErrorLabel);
    loginContentPanel.add(filler3);

    loginButton.setBackground(new java.awt.Color(51, 51, 255));
    loginButton.setForeground(new java.awt.Color(255, 255, 255));
    loginButton.setText("Login");
    loginButton.setBorder(null);
    loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    loginButton.setPreferredSize(new java.awt.Dimension(73, 23));
    loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            loginButtonMousePressed(evt);
        }
    });
    loginContentPanel.add(loginButton);

    registerButton.setBackground(new java.awt.Color(51, 51, 255));
    registerButton.setForeground(new java.awt.Color(255, 255, 255));
    registerButton.setText("Register");
    registerButton.setBorder(null);
    registerButton.setPreferredSize(new java.awt.Dimension(73, 23));
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            registerButtonMousePressed(evt);
        }
    });
    loginContentPanel.add(registerButton);

    loginPaddingPanel.add(loginContentPanel);

    loginPagePanel.add(loginPaddingPanel, "card2");

    windowPanel.add(loginPagePanel, java.awt.BorderLayout.CENTER);

    getContentPane().add(windowPanel, java.awt.BorderLayout.CENTER);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAccountInfoActionPerformed
        /// TODO: Create a window that will let the user edit their information and save it
    }//GEN-LAST:event_btnUpdateAccountInfoActionPerformed

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        
        usernameFieldErrorLabel.setText("");
        passwordFieldErrorLabel.setText("");
        
        String usernameInput = usernameField.getText();
        String passwordInput = new String(passwordField.getPassword());
        boolean isUserFound = false;
                
        for (User user : users) {
            if (user.username.equals(usernameInput)) {
                isUserFound = true;
                if (user.password.equals(passwordInput)) {
                    currentUser = user;
                    initMenu();
                    return;
                }
            }
        }
        
        if (!isUserFound) {
            usernameFieldErrorLabel.setText("Username not found");
        }
        
        passwordFieldErrorLabel.setText("Invalid password");
       
    }//GEN-LAST:event_loginButtonMousePressed

    private void registerButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMousePressed
        
        loginPaddingPanel.remove(loginContentPanel);
        loginPaddingPanel.add(regUserTypeContentPanel);        
        
        revalidate();
        repaint();
        
    }//GEN-LAST:event_registerButtonMousePressed

    private void registerSubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerSubmitButtonMousePressed
        /*
         * DEV NOTE: All fields still do not check if inputs are valid or not
         *           (ex. if name has no numbers, if email address is valid, 
         *           etc.) Please take note of this for future testing
         */
        
        HashMap<String, String> data =  new HashMap<>();
        
        confirmPassFieldErrorLabel.setText("");
        
        // Cancel account creation if any field is empty
        if (Helpers.checkForEmptyFields(registerContentPanel)) {
            return;
        }
        
        /*
         * Checks if both password fields are the same. If not, the program
         * notifies the user about the error and does not proceed with account
         * creation
         */
        String pass1 = new String(regPasswordField.getPassword());
        String pass2 = new String(confirmPassField.getPassword());
        if (pass1.equals(pass2) == false) {
            confirmPassFieldErrorLabel.setText("Password does not match");
            return;
        } 
        
        data.put("firstName", firstNameField.getText());
        data.put("middleName", middleNameField.getText());
        data.put("lastName", lastNameField.getText());
        data.put("email", emailField.getText());
        data.put("contactNumber", contactNumField.getText());
        data.put("username", regUsernameField.getText());
        data.put("name", data.get("firstName") + " " + data.get("middleName") 
                + " " + data.get("lastName"));
            
        javax.swing.JLabel msg = new javax.swing.JLabel(String.format(
            "<html><p>Please confirm your details:</p>" +
            "<p>Username: %s</p>" +
            "<p>Password: %s</p>" +
            "<p>First name: %s</p>" +
            "<p>Middle name: %s</p>" +
            "<p>Last name: %s</p>" +
            "<p>Email: %s</p>" +
            "<p>Contact Number: %s</p></html>",
            data.get("firstName"), data.get("password").replaceAll(".", "*"),
            data.get("firstName"), data.get("middleName"), 
            data.get("lastName"), data.get("email"),
            data.get("contactNumber")
        ));
        
        int confirmation = JOptionPane.showConfirmDialog(null, msg, "Register", 
            JOptionPane.OK_CANCEL_OPTION);
        
        if (confirmation == 0) {
            Client newClient = new Client(data);
                    
            // Add the created user to the list of users
            users.add(newClient);
        
            newClient.saveUserData();
            
            JOptionPane.showMessageDialog(null, "Account successfully created");
            
            loginPaddingPanel.remove(registerContentPanel);
            loginPaddingPanel.add(loginContentPanel);
            
            revalidate();
            repaint();            
        }
        
        /*
        CODE SNIPPET: Clear all fields
        
        DEV NOTE: Maybe implement a clearAllTextFields function next time?
        
            firstNameField.setText("");
            middleNameField.setText("");
            lastNameField.setText("");
            emailField.setText("");
            contactNumField.setText("");
            regUsernameField.setText("");
            regPasswordField.setText("");
            confirmPassField.setText("");
        */
        
    }//GEN-LAST:event_registerSubmitButtonMousePressed

    private void menuPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuPageToggleButtonItemStateChanged
        activePage = menuPagePanel;
        updateMenu();
    }//GEN-LAST:event_menuPageToggleButtonItemStateChanged

    private void applicationPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_applicationPageToggleButtonItemStateChanged
        activePage = applicationPagePanel;
        updateMenu();
    }//GEN-LAST:event_applicationPageToggleButtonItemStateChanged

    private void paymentPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentPageToggleButtonItemStateChanged
        activePage = paymentPagePanel;
        updateMenu();
    }//GEN-LAST:event_paymentPageToggleButtonItemStateChanged

    private void statusPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusPageToggleButtonItemStateChanged
        activePage = statusPagePanel;
        updateMenu();
    }//GEN-LAST:event_statusPageToggleButtonItemStateChanged

    private void reportPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reportPageToggleButtonItemStateChanged
        activePage = reportPagePanel;
        updateMenu();
    }//GEN-LAST:event_reportPageToggleButtonItemStateChanged

    private void searchPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchPageToggleButtonItemStateChanged
        activePage = searchPagePanel;
        updateMenu();
    }//GEN-LAST:event_searchPageToggleButtonItemStateChanged

    private void aboutPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_aboutPageToggleButtonItemStateChanged
        activePage = aboutPagePanel;
        updateMenu();
    }//GEN-LAST:event_aboutPageToggleButtonItemStateChanged

    private void repaymentPageToggleButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_repaymentPageToggleButtonItemStateChanged
        activePage = repaymentPagePanel;                
        updateMenu();
    }//GEN-LAST:event_repaymentPageToggleButtonItemStateChanged

    private void regClientButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regClientButtonMousePressed
        userType = 0;
        
        loginPaddingPanel.remove(regUserTypeContentPanel);
        loginPaddingPanel.add(registerContentPanel);        
        
        revalidate();
        repaint();
    }//GEN-LAST:event_regClientButtonMousePressed

    private void regAdminButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regAdminButtonMousePressed
        userType = 1;
        
        loginPaddingPanel.remove(regUserTypeContentPanel);
        loginPaddingPanel.add(registerContentPanel);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_regAdminButtonMousePressed

    private void regAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAdminButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regAdminButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchSubmitButtonActionPerformed

    private void backToLoginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginButtonMousePressed
        loginPaddingPanel.remove(registerContentPanel);
        loginPaddingPanel.add(loginContentPanel);
        
        revalidate();
        repaint();
    }//GEN-LAST:event_backToLoginButtonMousePressed

    // This function is called to instantiate the menu with user details when
    // login is successful
    private void initMenu() {
        
        windowPanel.removeAll();
        backgroundPanel.removeAll();
        
        dashAccountNameLabel.setText(currentUser.firstName);
        dashEmailLabel.setText(currentUser.email);
        //dashContactNumLabel.setText(currentUser.contactNumber);

        activePage = menuPagePanel;
        updateMenu();
    }
    
    private void updateMenu() {
        
        windowPanel.removeAll();
        backgroundPanel.removeAll();
        
        backgroundPanel.add(menuBarPanel);
        backgroundPanel.add(activePage);
        
        windowPanel.add(backgroundPanel);
                    
        revalidate();
        repaint(); 
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {    
                
                GUI window = new GUI();                                
                
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPagePanel;
    private javax.swing.JToggleButton aboutPageToggleButton;
    private javax.swing.JPanel applicationContentPanel;
    private javax.swing.JPanel applicationPaddingPanel;
    private javax.swing.JPanel applicationPagePanel;
    private javax.swing.JToggleButton applicationPageToggleButton;
    private javax.swing.JLabel applyForALoanLabel;
    private javax.swing.JButton backToLoginButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton btnUpdateAccountInfo;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPassFieldErrorLabel;
    private javax.swing.JTextField contactNumField;
    private javax.swing.JLabel dashAccountNameLabel;
    private javax.swing.JLabel dashAccountNumLabel;
    private javax.swing.JLabel dashContactNumLabel;
    private javax.swing.JLabel dashEmailLabel;
    private javax.swing.JPanel dashboardContent;
    private javax.swing.JTextField emailField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lblAccountInfo;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginContentPanel;
    private javax.swing.JLabel loginGraphicLabel;
    private javax.swing.JPanel loginGraphicsPanel;
    private javax.swing.JPanel loginPaddingPanel;
    private javax.swing.JPanel loginPagePanel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.ButtonGroup menuButtonGroup;
    private javax.swing.JPanel menuPagePanel;
    private javax.swing.JToggleButton menuPageToggleButton;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordFieldErrorLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel paymentPagePanel;
    private javax.swing.JToggleButton paymentPageToggleButton;
    private javax.swing.JLabel programNameLabel;
    private javax.swing.JButton regAdminButton;
    private javax.swing.JButton regClientButton;
    private javax.swing.JLabel regConfirmPassLabel;
    private javax.swing.JLabel regContactNumLabel;
    private javax.swing.JLabel regEmailLabel;
    private javax.swing.JLabel regFirstNameLabel;
    private javax.swing.JLabel regLastNameLabel;
    private javax.swing.JLabel regMiddleNameLabel;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JLabel regPasswordLabel;
    private javax.swing.JPanel regUserTypeContentPanel;
    private javax.swing.JTextField regUsernameField;
    private javax.swing.JLabel regUsernameLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerContentPanel;
    private javax.swing.JButton registerSubmitButton;
    private javax.swing.JLabel registrationLabel;
    private javax.swing.JPanel repaymentPagePanel;
    private javax.swing.JToggleButton repaymentPageToggleButton;
    private javax.swing.JPanel reportPagePanel;
    private javax.swing.JToggleButton reportPageToggleButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPagePadding;
    private javax.swing.JPanel searchPagePanel;
    private javax.swing.JToggleButton searchPageToggleButton;
    private javax.swing.JLabel searchResultsLabel;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JScrollPane searchResultsScrollPane;
    private javax.swing.JButton searchSubmitButton;
    private javax.swing.JPanel statusPagePanel;
    private javax.swing.JToggleButton statusPageToggleButton;
    private javax.swing.JButton submitApplicationButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameFieldErrorLabel;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables
}

class searchResultEntry extends javax.swing.JPanel {
    
    javax.swing.JPanel clientDetailsPanel = new javax.swing.JPanel();
    javax.swing.JLabel usernameLabel = new javax.swing.JLabel();
    javax.swing.JLabel nameLabel = new javax.swing.JLabel();
    javax.swing.JLabel emailLabel = new javax.swing.JLabel();
    javax.swing.JLabel accountNumberLabel = new javax.swing.JLabel();
    javax.swing.JLabel contactNumberLabel = new javax.swing.JLabel();
    javax.swing.JSeparator vertSeparator = new javax.swing.JSeparator();
    javax.swing.JButton btn = new javax.swing.JButton();
    
    public searchResultEntry() {
        setPreferredSize(new java.awt.Dimension(880, 70));
        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        
        clientDetailsPanel.setOpaque(false);
        clientDetailsPanel.setPreferredSize(new java.awt.Dimension(800, 60));
        clientDetailsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("Username: renz.flores");
        usernameLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        clientDetailsPanel.add(usernameLabel);

        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("Name: Renz Ken T. Flores");
        nameLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        clientDetailsPanel.add(nameLabel);

        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email: renz.flores@gmail.com");
        emailLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        clientDetailsPanel.add(emailLabel);

        accountNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        accountNumberLabel.setText("Account Number: 123456");
        accountNumberLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        clientDetailsPanel.add(accountNumberLabel);

        contactNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        contactNumberLabel.setText("Contact Number: 1234567890");
        contactNumberLabel.setPreferredSize(new java.awt.Dimension(200, 16));
        clientDetailsPanel.add(contactNumberLabel);
        add(clientDetailsPanel);
        
        vertSeparator.setForeground(new java.awt.Color(204, 204, 204));
        vertSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vertSeparator.setPreferredSize(new java.awt.Dimension(5, 50));
        add(vertSeparator);
        
        btn.setPreferredSize(new java.awt.Dimension(40, 40));
        btn.setBorder(null);
        btn.setOpaque(false);
        btn.setIcon(Helpers.resizeIcon("detailsArrow", 40, 40));
        btn.setText("Choose file");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
        });
        add(btn);
    }    
    
    private void btnMousePressed(java.awt.event.MouseEvent evt) {
        
        javax.swing.JOptionPane userDetailsPane = new javax.swing.JOptionPane();
        
        userDetailsPane.showMessageDialog(null, "test");
    }
           
}
    
class ImageFileChooser extends javax.swing.JPanel {
    
    javax.swing.JButton btn = new javax.swing.JButton();
    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    javax.swing.JLabel fileLabel = new javax.swing.JLabel("No file chosen");
    java.io.File file;
    java.awt.Image img;
    
    public ImageFileChooser() {
        
        btn.setBackground(new java.awt.Color(152, 152, 152));
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setPreferredSize(new java.awt.Dimension(80, 20));
        btn.setBorder(null);
        btn.setText("Choose file");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMousePressed(evt);
            }
        });
        
        fileLabel.setForeground(new java.awt.Color(0, 0, 0));
        
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Choose file");        
        fc.addChoosableFileFilter(new 
            javax.swing.filechooser.FileNameExtensionFilter(
            "Image Files (.jpg, .png)", "jpg", "png"));        
        fc.setPreferredSize(new java.awt.Dimension(500, 400));
        
        setPreferredSize(new java.awt.Dimension(200, 24));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
        setOpaque(false);
        add(btn);
        add(fileLabel);
    }
    
    private void btnMousePressed(java.awt.event.MouseEvent evt) {                                      
        int returnVal = fc.showOpenDialog(null);
        
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                
                try {
                    img = javax.imageio.ImageIO.read(file);
                } 
                catch (java.io.IOException e) {
                    e.printStackTrace();
                }
                
                fileLabel.setText(file.getName());
        }
    }
    
    public java.awt.Image getImage() {
        return img;
    }
    
    public String getFileDirectory() {
        return file.getAbsolutePath();
    }
    
}

class TransactionEntryPanel extends javax.swing.JPanel {
    
    javax.swing.JPanel panelContent = new javax.swing.JPanel();
    javax.swing.JLabel dateTimeLabel = new javax.swing.JLabel();
    javax.swing.JLabel amountLabel = new javax.swing.JLabel();
    javax.swing.JLabel refIDLabel = new javax.swing.JLabel();
    javax.swing.JLabel statusLabel = new javax.swing.JLabel();

    public TransactionEntryPanel(String dateTime, String amount,
        String refID, String status) {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 60));
        setLayout(new java.awt.CardLayout(5, 5));
        
        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setPreferredSize(new java.awt.Dimension(900, 60));
        panelContent.setLayout(new java.awt.CardLayout(5, 5));

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setPreferredSize(new java.awt.Dimension(450, 60));
        panelContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        dateTimeLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateTimeLabel.setText(dateTime);
        dateTimeLabel.setPreferredSize(new java.awt.Dimension(200, 16));
        panelContent.add(dateTimeLabel);
       
        insertSeparator();

        amountLabel.setForeground(new java.awt.Color(0, 0, 0));
        amountLabel.setText(amount);
        amountLabel.setPreferredSize(new java.awt.Dimension(210, 16));
        panelContent.add(amountLabel);
        
        insertSeparator();

        refIDLabel.setForeground(new java.awt.Color(0, 0, 0));
        refIDLabel.setText(refID);
        refIDLabel.setPreferredSize(new java.awt.Dimension(210, 16));
        panelContent.add(refIDLabel);
        
        insertSeparator();

        statusLabel.setBackground(new java.awt.Color(0, 255, 0));
        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText(status);
        statusLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true)));
        statusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statusLabel.setOpaque(true);
        statusLabel.setPreferredSize(new java.awt.Dimension(70, 24));
        panelContent.add(statusLabel);

        add(panelContent, "card2");
    }
    
    private void insertSeparator() {
        javax.swing.JSeparator vertSeparator = new javax.swing.JSeparator();
        
        vertSeparator.setForeground(new java.awt.Color(204, 204, 204));
        vertSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        vertSeparator.setMinimumSize(new java.awt.Dimension(10, 100));
        vertSeparator.setPreferredSize(new java.awt.Dimension(5, 50));
        
        panelContent.add(vertSeparator);
    }

}